In [1]:
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
np.random.seed(13)
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout
from keras import optimizers
import pandas as pd
import matplotlib.pyplot as plt
import math
from __future__ import division

from sklearn.preprocessing import normalize
from stockstats import StockDataFrame 
from googlefinance.client import get_price_data, get_prices_data, get_prices_time_data

import dataPreparation
files=['TSLA','AAPL','ADBE','ADI','GOOGL']
prices=list()
for file in files:
    param = {
        'q': file, # Stock symbol (ex: "AAPL")
        'i': "3600", # Interval size in seconds ("86400" = 1 day intervals)
        'x': "NASD", # INDEXNASDAQStock exchange symbol on which stock is traded (ex: "NASD")
        'p': "2Y" # Period (Ex: "1Y" = 1 year)
        }

    # link to doc http://www.networkerror.org/component/content/article/1-technical-wootness/44-googles-undocumented-finance-api.html
    # get price data (return pandas dataframe) 1465948800
    priceData = get_price_data(param)
    #print(priceData)
    stock = StockDataFrame.retype(priceData)
    #print(stock)
    string=['volume_-2_d','volume_-4_d','volume_-6_d','volume_-8_d','volume_-10_d','volume_-12_d''macd','macds','kdjk','kdjd','kdjj','tr','atr','wr_2','wr_10','wr_6','wr_8','wr_12','wr_14','close_-2_d','close_-4_d','close_-6_d','close_-8_d','close_-10_d','close_-12_d','close_-14_d','close_-16_d','rsi_2','rsi_4','rsi_6','rsi_8','rsi_10','rsi_12','rsi_14','rsi_16']

    #['macd','macds', 'boll_ub', 'boll_lb','rsi_6','rsi_12','vr_6_sma','wr_10','wr_6''close_10_sma''tr''middle_{}_sma'
    #df['dma'] = df['close_10_sma'] - df['close_50_sma'] pdi'] = cls._get_pdi(df, 14)df['mdi'] = cls._get_mdi(df, 14)
    #df['dx'] = cls._get_dx(df, 14) df['adx'] = df['dx_6_ema'] df['adxr'] = df['adx_6_ema']]
    #



    stock.get(string)
    price=stock
    print(price)
    print('---------------------------------------------------------------------------------------------------')
    prices.append(price)

/home/andrea/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/home/andrea/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:194: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
/home/andrea/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:194: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_inde

                         open      high       low     close   volume  \
2016-05-05 22:00:00  228.4600  228.6400  217.5000  219.4000  2212467   
2016-05-05 23:00:00  219.2800  220.4300  211.9900  213.6100  2483966   
2016-05-06 00:00:00  213.6200  216.2900  211.7300  214.5300  1057163   
2016-05-06 01:00:00  214.5900  216.0000  212.8700  213.8278   676221   
2016-05-06 02:00:00  213.7800  213.9600  209.7900  211.3300   871506   
2016-05-06 03:00:00  211.2850  214.4300  211.0600  213.3900   711883   
2016-05-06 04:00:00  213.4000  213.7300  210.8000  211.5300  1241066   
2016-05-06 22:00:00  210.8700  212.8650  208.1100  210.3225  1187954   
2016-05-06 23:00:00  210.0801  213.5000  209.2101  210.0800  1053097   
2016-05-07 00:00:00  210.1000  212.9600  210.0200  212.3900   566207   
2016-05-07 01:00:00  212.4000  214.6200  211.4600  214.6100   434421   
2016-05-07 02:00:00  214.5840  216.3700  214.5300  215.5000   627764   
2016-05-07 03:00:00  215.4600  216.1100  214.6700  215.2400   39

['volume_-2_d', 'volume_-4_d', 'volume_-6_d', 'volume_-8_d', 'volume_-10_d', 'volume_-12_dmacd', 'macds', 'kdjk', 'kdjd', 'kdjj', 'tr', 'atr', 'wr_2', 'wr_10', 'wr_6', 'wr_8', 'wr_12', 'wr_14', 'close_-2_d', 'close_-4_d', 'close_-6_d', 'close_-8_d', 'close_-10_d', 'close_-12_d', 'close_-14_d', 'close_-16_d', 'rsi_2', 'rsi_4', 'rsi_6', 'rsi_8', 'rsi_10', 'rsi_12', 'rsi_14', 'rsi_16'] not found.
Traceback (most recent call last):
  File "/home/andrea/anaconda3/lib/python3.6/site-packages/stockstats.py", line 922, in __getitem__
    super(StockDataFrame, self).__getitem__(item))
  File "/home/andrea/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2133, in __getitem__
    return self._getitem_array(key)
  File "/home/andrea/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2177, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/home/andrea/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1269, in _conver

                         open      high       low     close    volume  \
2016-05-05 22:00:00   94.0000   94.0700   93.0000   93.0800   5062263   
2016-05-05 23:00:00   93.0800   93.5400   92.8300   93.2000   5960098   
2016-05-06 00:00:00   93.2100   93.4400   93.0400   93.1753   3466896   
2016-05-06 01:00:00   93.1800   93.3100   92.9100   92.9699   2923989   
2016-05-06 02:00:00   92.9665   93.0100   92.6800   92.8600   3895898   
2016-05-06 03:00:00   92.8684   93.2000   92.7150   92.9850   3494124   
2016-05-06 04:00:00   92.9850   93.2400   92.8600   93.2400   7853954   
2016-05-06 22:00:00   93.3700   93.4500   92.8100   93.0550   3902026   
2016-05-06 23:00:00   93.0550   93.4300   92.5100   92.6300   5538978   
2016-05-07 00:00:00   92.6300   93.0000   92.1000   92.1950   5931797   
2016-05-07 01:00:00   92.1990   92.3200   91.9900   92.2100   5797909   
2016-05-07 02:00:00   92.2170   92.4700   91.8500   92.2292   5840689   
2016-05-07 03:00:00   92.2300   92.8000   92.2100  

['volume_-2_d', 'volume_-4_d', 'volume_-6_d', 'volume_-8_d', 'volume_-10_d', 'volume_-12_dmacd', 'macds', 'kdjk', 'kdjd', 'kdjj', 'tr', 'atr', 'wr_2', 'wr_10', 'wr_6', 'wr_8', 'wr_12', 'wr_14', 'close_-2_d', 'close_-4_d', 'close_-6_d', 'close_-8_d', 'close_-10_d', 'close_-12_d', 'close_-14_d', 'close_-16_d', 'rsi_2', 'rsi_4', 'rsi_6', 'rsi_8', 'rsi_10', 'rsi_12', 'rsi_14', 'rsi_16'] not found.
Traceback (most recent call last):
  File "/home/andrea/anaconda3/lib/python3.6/site-packages/stockstats.py", line 922, in __getitem__
    super(StockDataFrame, self).__getitem__(item))
  File "/home/andrea/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2133, in __getitem__
    return self._getitem_array(key)
  File "/home/andrea/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2177, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/home/andrea/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1269, in _conver

                         open      high       low     close  volume  \
2016-05-05 22:00:00   93.1000   93.8600   92.9200   92.9300  134714   
2016-05-05 23:00:00   92.9650   93.8225   92.9200   93.6600  181684   
2016-05-06 00:00:00   93.6800   94.2165   93.4200   94.0200  181164   
2016-05-06 01:00:00   94.0000   94.1200   93.7900   93.9600  137149   
2016-05-06 02:00:00   93.9450   93.9772   93.3200   93.3300  226399   
2016-05-06 03:00:00   93.3300   93.5900   93.2000   93.2800  215309   
2016-05-06 04:00:00   93.2600   93.5500   93.1500   93.5000  506651   
2016-05-06 22:00:00   93.1300   93.8800   93.0501   93.1800  132892   
2016-05-06 23:00:00   93.1100   93.2800   92.5700   92.6660  143488   
2016-05-07 00:00:00   92.6200   93.1300   92.6200   92.8600   97047   
2016-05-07 01:00:00   92.8500   93.2900   92.7900   93.2300   87436   
2016-05-07 02:00:00   93.2400   94.0900   93.1300   94.0650  160499   
2016-05-07 03:00:00   94.1000   94.4000   94.0000   94.2570  183022   
2016-0

['volume_-2_d', 'volume_-4_d', 'volume_-6_d', 'volume_-8_d', 'volume_-10_d', 'volume_-12_dmacd', 'macds', 'kdjk', 'kdjd', 'kdjj', 'tr', 'atr', 'wr_2', 'wr_10', 'wr_6', 'wr_8', 'wr_12', 'wr_14', 'close_-2_d', 'close_-4_d', 'close_-6_d', 'close_-8_d', 'close_-10_d', 'close_-12_d', 'close_-14_d', 'close_-16_d', 'rsi_2', 'rsi_4', 'rsi_6', 'rsi_8', 'rsi_10', 'rsi_12', 'rsi_14', 'rsi_16'] not found.
Traceback (most recent call last):
  File "/home/andrea/anaconda3/lib/python3.6/site-packages/stockstats.py", line 922, in __getitem__
    super(StockDataFrame, self).__getitem__(item))
  File "/home/andrea/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2133, in __getitem__
    return self._getitem_array(key)
  File "/home/andrea/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2177, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/home/andrea/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1269, in _conver

                        open     high      low    close   volume  volume_-2_s  \
2016-05-05 22:00:00  55.9800  56.1500  55.4200  55.6100   101863          NaN   
2016-05-05 23:00:00  55.6600  56.0200  55.6300  56.0100    86013          NaN   
2016-05-06 00:00:00  56.0000  56.2100  55.9200  56.0200    92007     101863.0   
2016-05-06 01:00:00  56.0600  56.1200  55.9300  56.0500    66369      86013.0   
2016-05-06 02:00:00  56.0200  56.0294  55.7300  55.8700   111820      92007.0   
2016-05-06 03:00:00  55.8600  56.0000  55.8300  55.9300   125524      66369.0   
2016-05-06 04:00:00  55.9200  55.9250  55.6900  55.6900   756344     111820.0   
2016-05-06 22:00:00  55.4700  55.5900  54.8500  55.5200   148396     125524.0   
2016-05-06 23:00:00  55.5400  55.6800  55.0100  55.0800   193545     756344.0   
2016-05-07 00:00:00  55.0700  55.2000  54.8550  54.8901   153568     148396.0   
2016-05-07 01:00:00  54.8950  55.0500  54.8400  55.0275   275585     193545.0   
2016-05-07 02:00:00  55.0300

['volume_-2_d', 'volume_-4_d', 'volume_-6_d', 'volume_-8_d', 'volume_-10_d', 'volume_-12_dmacd', 'macds', 'kdjk', 'kdjd', 'kdjj', 'tr', 'atr', 'wr_2', 'wr_10', 'wr_6', 'wr_8', 'wr_12', 'wr_14', 'close_-2_d', 'close_-4_d', 'close_-6_d', 'close_-8_d', 'close_-10_d', 'close_-12_d', 'close_-14_d', 'close_-16_d', 'rsi_2', 'rsi_4', 'rsi_6', 'rsi_8', 'rsi_10', 'rsi_12', 'rsi_14', 'rsi_16'] not found.
Traceback (most recent call last):
  File "/home/andrea/anaconda3/lib/python3.6/site-packages/stockstats.py", line 922, in __getitem__
    super(StockDataFrame, self).__getitem__(item))
  File "/home/andrea/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2133, in __getitem__
    return self._getitem_array(key)
  File "/home/andrea/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2177, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/home/andrea/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1269, in _conver

                          open       high        low      close  volume  \
2016-05-05 22:00:00   715.0000   717.5500   711.3040   712.4700  141934   
2016-05-05 23:00:00   712.3200   715.0000   710.8700   713.8500  109711   
2016-05-06 00:00:00   713.5300   716.1900   712.2100   714.4200   90909   
2016-05-06 01:00:00   714.6200   715.3900   712.1200   712.9000   69478   
2016-05-06 02:00:00   712.8700   713.5000   709.4501   712.3411  109822   
2016-05-06 03:00:00   712.5100   715.3200   711.4200   713.6400  134265   
2016-05-06 04:00:00   713.8500   715.0000   712.7200   714.7100  336231   
2016-05-06 22:00:00   712.2000   718.1200   711.9500   716.5500  157175   
2016-05-06 23:00:00   717.0700   720.4100   715.5900   718.1000  284082   
2016-05-07 00:00:00   717.9482   720.8400   716.8400   718.5800  170318   
2016-05-07 01:00:00   718.5400   720.2400   718.0700   720.0600   90819   
2016-05-07 02:00:00   720.1267   723.8100   719.7600   723.7200  119696   
2016-05-07 03:00:00   723

In [ ]:
from keras import backend as K

def f1(y_true, y_pred):
    def recall(y_true, y_pred):
        """Recall metric.

        Only computes a batch-wise average of recall.

        Computes the recall, a metric for multi-label classification of
        how many relevant items are selected.
        """
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
        recall = true_positives / (possible_positives + K.epsilon())
        return recall

    def precision(y_true, y_pred):
        """Precision metric.

        Only computes a batch-wise average of precision.

        Computes the precision, a metric for multi-label classification of
        how many selected items are relevant.
        """
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
        precision = true_positives / (predicted_positives + K.epsilon())
        return precision
    precision = precision(y_true, y_pred)
    recall = recall(y_true, y_pred)
    return 2*((precision*recall)/(precision+recall+K.epsilon()))

def findMaxAcc(valacc,valloss):
	prevloss=valloss[0]
	for i in range(1,len(valloss)):
		if(valloss[i]>prevloss):
			return valacc[i-1]
	#print('Problems with find MaxAccuracy')
	return valacc[len(valacc)-1]


In [ ]:
def f1score(y_true, y_pred):
    print(f1_score(y_true,y_pred))
    return np.array(f1_score(y_true,y_pred))

def buildModel(l,n):
    opt=keras.optimizers.SGD(lr=l, momentum=0.0, decay=0.0, nesterov=False)
    model = Sequential()
    model.add(Dense(15, input_shape=(15,), activation='sigmoid'))
    model.add(Dense(n))
    model.add(Dense(n))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy',f1])
    return model
o=0
accstocksresults=[]
f1stocksresults=[]

for price in prices:
    #print('New price[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]')
    
   
    print('Working on...',files[o])
    o+=1
    xtemp=price
    xtemp=np.nan_to_num(np.asarray(xtemp, dtype=float))
    xtemp=normalize(xtemp,axis=0,norm='max')
    #print(xtemp)
    accintime=[]
    trendwindowtime=[2,4,6,10,16,24,32,42,56,66,87,100,112,125,140,160,175,190,205,220,245,260,300,350,400]
    f1total=[]
    acctotal=[]
    for t in trendwindowtime:
        #1
    #label because of the maket and append values without data
    #simo theroy past trend
        
        x=[]
        y=[]
        

        #print('============================================================')
        #print('Working on window:',t)
        #print(len(xtemp))
        ##QUI C E L'UNICO APPUNTO GUARDA SE CON +1 CAMBIA
        for i in range(0,len(price)-t-1):
            y.append(np.sign(price.iloc[i+t+1]['close']-price.iloc[i+1]['open']))
            x.append(xtemp[i])
        y=np.array(y)
        y=(y+1)//2
        x=np.array(x)
        permindex=range(0,len(x))
        #permindex=np.random.permutation(permindex)
        train=0.8
        nt=math.ceil(len(x)*train)
        trainvalindex=permindex[0:nt]
        testindex=permindex[nt:]
        x_tv=[]
        y_tv=[]
        x_test=[]
        y_test=[]
        x_tv=x[trainvalindex]
        y_tv=y[trainvalindex]
        x_test=x[testindex]
        y_test=y[testindex]
    

        units=[8,16,32]
        learning=[0.01,0.0001,0.00001]
        bestsvm=None
        maxacc=0
        cvacc=0
        maxu=0
        maxl=0
        #print('Model Selection...')
        #model selection
        cvacc=0
        for n in units:
            #print()
            for l in learning:
                
                cvacclist=[]
                #faccio cross validation
                #start with 40% as train and 10% for validation and then i move in percentege
                # 0-40 40-50
                # 0-50 50-60
                # 0-60 60-70 
                #etc test set is completely external i do in some way error extimation changin the ticker
                trainpoint=math.floor(len(x_tv)*0.40)
                dimval=math.floor(trainpoint*0.25)
                endval=trainpoint+dimval
                
                for i in range(0,6):
                    #print('-----')
                    x_train=x_tv[0:trainpoint]
                    y_train=y_tv[0:trainpoint]
                    x_val=x_tv[trainpoint:endval]
                    y_val=y_tv[trainpoint:endval]
                    #print(trainpoint)
                    #print(endval)
                    #print(len(x_tv))
                    trainpoint=trainpoint+dimval
                    endval=endval+dimval
                    model=buildModel(l,n)
                    p=sum(y_train)/len(y_train)
                    history=model.fit(x_train, y_train, class_weight={0 :p,1:1-p},epochs=20,shuffle=False, verbose=0,batch_size=10,validation_data=(x_val, y_val))
                    maxAcc=findMaxAcc(history.history['val_acc'],history.history['val_loss'])
                    cvacclist.append(maxAcc)
                cvacc=sum(cvacclist)/len(cvacclist)
                if(cvacc>maxacc):
                    #print(cvacc)
                    maxacc=cvacc
                    maxl=l
                    maxu=n
        
       
        model=buildModel(maxl,maxu)
        p=sum(y_tv)/len(y_tv)
        model.fit(x_tv, y_tv, class_weight={0 :p,1:1-p}, epochs=20,shuffle=False, verbose=0,batch_size=10)
        #print(model.evaluate(x=x_test, y=y_test, batch_size=10, verbose=0))
        prediction=model.predict(x=x_test)
        confmatrix=confusion_matrix(y_test, np.rint(prediction))
        print(confmatrix)
        loss,valueacc,CM=model.evaluate(x=x_test, y=y_test, batch_size=10, verbose=0)
        print(t)
        print('F1,score',CM)
        print('Accuracy:',valueacc)
        f1total.append(CM)
        acctotal.append(valueacc)
    print(f1total)
    print(acctotal)
    print('accuracy')
    plt.plot(trendwindowtime,acctotal)
    plt.show()
    print('f1score')
    plt.plot(trendwindowtime,f1total)
    plt.show()
    accstocksresults.append(acctotal)
    f1stocksresults.append(f1total)

Working on... TSLA
[[ 25 307]
 [ 35 335]]
2
F1,score 0.6207877330036244
Accuracy: 0.5128205190611701
[[347   0]
 [355   0]]
4
F1,score 0.0
Accuracy: 0.49430199455671503
[[261  96]
 [231 113]]
6
F1,score 0.21029029295549923
Accuracy: 0.533523539886325
[[342  12]
 [316  31]]
10
F1,score 0.08197322487831116
Accuracy: 0.5320970065753572
[[362   0]
 [337   0]]
16
F1,score 0.0
Accuracy: 0.5178826888743389
[[366   0]
 [332   0]]
24
F1,score 0.0
Accuracy: 0.5243552999843157
[[382   0]
 [314   0]]
32
F1,score 0.0
Accuracy: 0.5488505735565191
[[381   0]
 [313   0]]
42
F1,score 0.0
Accuracy: 0.5489913542736161
[[384   0]
 [307   0]]
56
F1,score 0.0
Accuracy: 0.5557163533055144
[[383   0]
 [303   3]]
66
F1,score 0.007476799287366936
Accuracy: 0.5602322204365613
[[381   0]
 [304   0]]
87
F1,score 0.0
Accuracy: 0.5562043798013325
[[  0 370]
 [  0 313]]
100
F1,score 0.4829888071968475
Accuracy: 0.45827232870664636
[[354   0]
 [326   0]]
112
F1,score 0.0
Accuracy: 0.5205882352722042
[[357   0]
 [321  