In [1]:
import numpy as np
from imblearn.over_sampling import SMOTE, ADASYN
import execute
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
np.random.seed(13)
from sklearn import svm
import pandas as pd
import matplotlib.pyplot as plt
import math
from __future__ import division
from sklearn.model_selection import KFold
from sklearn.preprocessing import normalize
from stockstats import StockDataFrame 
from googlefinance.client import get_price_data, get_prices_data, get_prices_time_data

import dataPreparation
files=['AAPL', 'ADBE', 'ADI', 'ADP', 'ADSK', 'AKAM', 'ALGN',
          'ALXN', 'AMAT', 'AMGN', 'AMZN', 'ATVI', 'AVGO', 'BIDU', 
          'BIIB', 'BMRN', 'CA', 'CELG', 'CERN', 'CHTR', 'CMCSA',
          'COST', 'CSCO', 'CSX', 'CTAS', 'CTRP', 'CTSH', 'CTXS',
          'DISCA', 'DISH', 'DLTR', 'EA', 'EBAY', 'ESRX', 'EXPE',
          'FAST', 'FB', 'FISV', 'FOXA', 'GILD', 'GOOGL', 'HAS',
          'HOLX', 'HSIC', 'IDXX', 'ILMN', 'INCY', 'INTC', 'INTU',
          'ISRG', 'JBHT', 'JD', 'KHC', 'KLAC', 'LBTYA', 'LRCX', 'MAR',
          'MAT', 'MCHP', 'MDLZ', 'MELI', 'MNST', 'MSFT', 'MU', 'MXIM',
          'MYL', 'NFLX', 'NTES', 'NVDA', 'ORLY', 'PAYX', 'PCAR', 'PCLN',
          'PYPL', 'QCOM', 'REGN', 'ROST', 'SBUX', 'SHPG', 'SIRI', 'STX',
          'SWKS', 'SYMC', 'TMUS', 'TSCO', 'TSLA', 'TXN', 'ULTA', 'VIAB',
          'VOD', 'VRSK', 'VRTX', 'WBA', 'WYNN', 'XLNX', 'XRAY']
prices=list()
sentiment=list()
for file in files:
    param = {
        'q': file, # Stock symbol (ex: "AAPL")
        'i': "900", # Interval size in seconds ("86400" = 1 day intervals)
        'x': "NASD", # INDEXNASDAQStock exchange symbol on which stock is traded (ex: "NASD")
        'p': "2Y" # Period (Ex: "1Y" = 1 year)
        }
    sentimentVector =  pd.read_csv('/home/andrea/Desktop/NLFF/TechnicalSentiment/'+file+'.csv')
    price= pd.read_csv('/home/andrea/Desktop/NLFF/TechnicalDataset/indexes'+file+'.csv')
    #alignment of data
    maxdata=max(sentimentVector['initTime'])
    mindata=min(sentimentVector['initTime'])
    price=price[price['Unnamed: 0']>=mindata]
    price=price[price['Unnamed: 0']<=maxdata]
    sentimentVector=sentimentVector.drop(['Unnamed: 0', 'initTime' ], axis=1)
    price=price.drop(['Unnamed: 0'],axis=1)
    #['macd','macds', 'boll_ub', 'boll_lb','rsi_6','rsi_12','vr_6_sma','wr_10','wr_6''close_10_sma''tr''middle_{}_sma'
    #df['dma'] = df['close_10_sma'] - df['close_50_sma'] pdi'] = cls._get_pdi(df, 14)df['mdi'] = cls._get_mdi(df, 14)
    #df['dx'] = cls._get_dx(df, 14) df['adx'] = df['dx_6_ema'] df['adxr'] = df['adx_6_ema']]
    #
    sentiment.append(sentimentVector)
    prices.append(price)

In [2]:
o=0
for price in prices:
    pricedec,pricepred,y_testp=execute.execPrice(price,files[o])
    newsdec,newspred,y_testn=execute.execNews(price,sentiment[o],files[o])
    pricedec=normalize(np.asarray(pricedec).reshape(-1,1),axis=0,norm='max')
    newsdec=normalize(np.asarray(newsdec).reshape(-1,1),axis=0,norm='max')
    o+=1
    
    finalprediction=[]
    for i in range(0,len(pricepred)):
        if(abs(newsdec[i])>abs(pricedec[i])):
            finalprediction.append(newspred[i])
        else:
            finalprediction.append(pricepred[i])
    final=confusion_matrix(y_testp, finalprediction)
    print('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
    print(final)
    from sklearn.metrics import accuracy_score
    facc=accuracy_score(y_testp, finalprediction)
    print(facc)
    print('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')


Working on price... AAPL
610.5402296585327
Window: 120
[[305   3]
 [227   7]]
Accuracy: 0.5756457564575646
[0.5756457564575646]
accuracy
Working on news... AAPL
10000.0
Window: 120
[[170 138]
 [105 129]]
Accuracy: 0.551660516605166
[0.551660516605166]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[305   3]
 [228   6]]
0.5738007380073801
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... ADBE
10000.0
Window: 120
[[278  29]
 [427 151]]
Accuracy: 0.4847457627118644
[0.4847457627118644]
accuracy
Working on news... ADBE
1291.5496650148827
Window: 120
[[173 134]
 [387 191]]
Accuracy: 0.41129943502824856
[0.41129943502824856]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[234  73]
 [426 152]]
0.43615819209039547
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... ADI
0.3593813663804626
Window: 120
[[125 359]
 [168 228]]
Accuracy: 0.4011363636363636
[0.4011363636363636]
accuracy
Working on news... ADI
372.7593720314938
Window: 120
[[101 383]
 [ 46 350]]
Accuracy: 0.5125
[0.5125]
accur

/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


1.0
Window: 120
[[459  11]
 [357  58]]
Accuracy: 0.584180790960452
[0.584180790960452]
accuracy
Working on news... ADP


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


1000.0
Window: 120
[[143 327]
 [152 263]]
Accuracy: 0.45875706214689266
[0.45875706214689266]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[466   4]
 [350  65]]
0.6
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... ADSK
51.7947467923121
Window: 120
[[326  56]
 [313 190]]
Accuracy: 0.5830508474576271
[0.5830508474576271]
accuracy
Working on news... ADSK
10000.0
Window: 120
[[ 10 372]
 [ 52 451]]
Accuracy: 0.5209039548022599
[0.5209039548022599]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[ 69 313]
 [200 303]]
0.42033898305084744
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... AKAM


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


610.5402296585327
Window: 120
[[259   7]
 [570  49]]
Accuracy: 0.3480225988700565
[0.3480225988700565]
accuracy
Working on news... AKAM


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


1000.0
Window: 120
[[224  42]
 [371 248]]
Accuracy: 0.5333333333333333
[0.5333333333333333]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[246  20]
 [547  72]]
0.3593220338983051
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... ALGN
0.3593813663804626
Window: 120
[[419   0]
 [451  15]]
Accuracy: 0.4903954802259887
[0.4903954802259887]
accuracy
Working on news... ALGN
610.5402296585327
Window: 120
[[134 285]
 [143 323]]
Accuracy: 0.5163841807909605
[0.5163841807909605]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[419   0]
 [447  19]]
0.49491525423728816
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... ALXN


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.000774263682681127
Window: 120
[[206 301]
 [ 88 290]]
Accuracy: 0.56045197740113
[0.56045197740113]
accuracy
Working on news... ALXN


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


21.54434690031882
Window: 120
[[367 140]
 [311  67]]
Accuracy: 0.4903954802259887
[0.4903954802259887]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[244 263]
 [126 252]]
0.56045197740113
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... AMAT


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.046415888336127774
Window: 120
[[278 151]
 [319 137]]
Accuracy: 0.4689265536723164
[0.4689265536723164]
accuracy
Working on news... AMAT


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.000774263682681127
Window: 120
[[243 186]
 [295 161]]
Accuracy: 0.45649717514124294
[0.45649717514124294]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[244 185]
 [312 144]]
0.4384180790960452
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... AMGN


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.046415888336127774
Window: 120
[[253  92]
 [436 104]]
Accuracy: 0.4033898305084746
[0.4033898305084746]
accuracy
Working on news... AMGN


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


1.637893706954064
Window: 120
[[244 101]
 [276 264]]
Accuracy: 0.5740112994350283
[0.5740112994350283]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[268  77]
 [432 108]]
0.4248587570621469
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... AMZN
0.000774263682681127
Window: 120
[[  5 182]
 [ 23 305]]
Accuracy: 0.6019417475728155
[0.6019417475728155]
accuracy
Working on news... AMZN
227.58459260747887
Window: 120
[[121  66]
 [195 133]]
Accuracy: 0.49320388349514566
[0.49320388349514566]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[ 12 175]
 [ 27 301]]
0.6077669902912621
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... ATVI
4.39397056076079
Window: 120
[[263   0]
 [622   0]]
Accuracy: 0.29717514124293787
[0.29717514124293787]
accuracy
Working on news... ATVI
1291.5496650148827
Window: 120
[[112 151]
 [362 260]]
Accuracy: 0.42033898305084744
[0.42033898305084744]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[263   0]
 [622   0]]
0.29717514124293787
!!!!!!!!!!!!!!!!!!!!!!!!!

/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


2.6826957952797255
Window: 120
[[315  96]
 [367 107]]
Accuracy: 0.4768361581920904
[0.4768361581920904]
accuracy
Working on news... BIDU


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


2.6826957952797255
Window: 120
[[246 165]
 [180 294]]
Accuracy: 0.6101694915254238
[0.6101694915254238]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[327  84]
 [313 161]]
0.5514124293785311
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... BIIB


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


11.787686347935873
Window: 120
[[383 188]
 [246  68]]
Accuracy: 0.5096045197740113
[0.5096045197740113]
accuracy
Working on news... BIIB


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


138.94954943731375
Window: 120
[[263 308]
 [153 161]]
Accuracy: 0.47909604519774013
[0.47909604519774013]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[379 192]
 [246  68]]
0.5050847457627119
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... BMRN


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


1.0
Window: 120
[[350 213]
 [199 118]]
Accuracy: 0.5318181818181819
[0.5318181818181819]
accuracy
Working on news... BMRN


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


7.196856730011519
Window: 120
[[136 427]
 [239  78]]
Accuracy: 0.2431818181818182
[0.2431818181818182]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[281 282]
 [216 101]]
0.4340909090909091
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... CA
4.39397056076079
Window: 120
[[249  22]
 [473 130]]
Accuracy: 0.43363844393592677
[0.43363844393592677]
accuracy
Working on news... CA
21.54434690031882
Window: 120
[[163 108]
 [234 369]]
Accuracy: 0.6086956521739131
[0.6086956521739131]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[181  90]
 [465 138]]
0.36498855835240274
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... CELG


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


84.83428982440716
Window: 120
[[329 258]
 [ 78 220]]
Accuracy: 0.6203389830508474
[0.6203389830508474]
accuracy
Working on news... CELG


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.0001
Window: 120
[[509  78]
 [210  88]]
Accuracy: 0.6745762711864407
[0.6745762711864407]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[500  87]
 [210  88]]
0.6644067796610169
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... CERN
21.54434690031882
Window: 120
[[383 198]
 [122 182]]
Accuracy: 0.6384180790960452
[0.6384180790960452]
accuracy
Working on news... CERN
372.7593720314938
Window: 120
[[155 426]
 [137 167]]
Accuracy: 0.3638418079096045
[0.3638418079096045]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[284 297]
 [130 174]]
0.5175141242937853
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... CHTR
0.3593813663804626
Window: 120
[[299  92]
 [247 236]]
Accuracy: 0.6121281464530892
[0.6121281464530892]
accuracy
Working on news... CHTR
1000.0
Window: 120
[[154 237]
 [202 281]]
Accuracy: 0.4977116704805492
[0.4977116704805492]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[292  99]
 [254 229]]
0.5961098398169337
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... C

/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


1.637893706954064
Window: 120
[[  5 355]
 [ 17 508]]
Accuracy: 0.5796610169491525
[0.5796610169491525]
accuracy
Working on news... CSCO


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.3593813663804626
Window: 120
[[ 94 266]
 [111 414]]
Accuracy: 0.5740112994350283
[0.5740112994350283]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[ 57 303]
 [ 50 475]]
0.6011299435028249
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... CSX
2.6826957952797255
Window: 120
[[528  27]
 [191 139]]
Accuracy: 0.7536723163841808
[0.7536723163841808]
accuracy
Working on news... CSX
0.000774263682681127
Window: 120
[[338 217]
 [292  38]]
Accuracy: 0.4248587570621469
[0.4248587570621469]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[506  49]
 [258  72]]
0.6531073446327683
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... CTAS
0.0001
Window: 120
[[201  77]
 [491 110]]
Accuracy: 0.35381114903299204
[0.35381114903299204]
accuracy
Working on news... CTAS
0.0001
Window: 120
[[202  76]
 [113 488]]
Accuracy: 0.7849829351535836
[0.7849829351535836]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[172 106]
 [414 187]]
0.40841865756541523
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price

/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


2.782559402207126
Window: 120
[[376   1]
 [503   5]]
Accuracy: 0.43050847457627117
[0.43050847457627117]
accuracy
Working on news... DISCA


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.046415888336127774
Window: 120
[[301  76]
 [321 187]]
Accuracy: 0.5514124293785311
[0.5514124293785311]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[376   1]
 [502   6]]
0.43163841807909603
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... DISH


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


10000.0
Window: 120
[[135 418]
 [ 47 269]]
Accuracy: 0.46490218642117376
[0.46490218642117376]
accuracy
Working on news... DISH


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


227.58459260747887
Window: 120
[[429 124]
 [194 122]]
Accuracy: 0.6340621403912543
[0.6340621403912543]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[277 276]
 [152 164]]
0.5074798619102416
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... DLTR


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


1291.5496650148827
Window: 120
[[159 329]
 [189 208]]
Accuracy: 0.41468926553672314
[0.41468926553672314]
accuracy
Working on news... DLTR


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.0001
Window: 120
[[  0 488]
 [  9 388]]
Accuracy: 0.4384180790960452
[0.4384180790960452]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[  0 488]
 [ 10 387]]
0.43728813559322033
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... EA
2.6826957952797255
Window: 120
[[381   1]
 [346 157]]
Accuracy: 0.607909604519774
[0.607909604519774]
accuracy
Working on news... EA
10000.0
Window: 120
[[254 128]
 [226 277]]
Accuracy: 0.6
[0.6]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[379   3]
 [318 185]]
0.6372881355932203
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... EBAY
51.7947467923121
Window: 120
[[252  18]
 [608   7]]
Accuracy: 0.29265536723163843
[0.29265536723163843]
accuracy
Working on news... EBAY
10000.0
Window: 120
[[162 108]
 [270 345]]
Accuracy: 0.5728813559322034
[0.5728813559322034]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[251  19]
 [606   9]]
0.2937853107344633
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... ESRX


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


51.7947467923121
Window: 120
[[ 10 473]
 [ 20 382]]
Accuracy: 0.4429378531073446
[0.4429378531073446]
accuracy
Working on news... ESRX


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


166.81005372000558
Window: 120
[[298 185]
 [339  63]]
Accuracy: 0.40790960451977404
[0.40790960451977404]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[204 279]
 [198 204]]
0.4610169491525424
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... EXPE
0.3593813663804626
Window: 120
[[129 353]
 [ 24 379]]
Accuracy: 0.5740112994350283
[0.5740112994350283]
accuracy
Working on news... EXPE
610.5402296585327
Window: 120
[[288 194]
 [145 258]]
Accuracy: 0.6169491525423729
[0.6169491525423729]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[186 296]
 [ 10 393]]
0.6542372881355932
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... FAST


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.3593813663804626
Window: 120
[[254 174]
 [233 197]]
Accuracy: 0.5256410256410257
[0.5256410256410257]
accuracy
Working on news... FAST


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


1000.0
Window: 120
[[ 95 333]
 [ 99 331]]
Accuracy: 0.4965034965034965
[0.4965034965034965]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[151 277]
 [120 310]]
0.5372960372960373
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... FB
610.5402296585327
Window: 120
[[340  41]
 [368 133]]
Accuracy: 0.536281179138322
[0.536281179138322]
accuracy
Working on news... FB
1000.0
Window: 120
[[247 134]
 [262 239]]
Accuracy: 0.5510204081632653
[0.5510204081632653]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[339  42]
 [347 154]]
0.5589569160997733
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... FISV
1000.0
Window: 120
[[242  41]
 [545  57]]
Accuracy: 0.33785310734463275
[0.33785310734463275]
accuracy
Working on news... FISV
1291.5496650148827
Window: 120
[[ 70 213]
 [158 444]]
Accuracy: 0.5807909604519774
[0.5807909604519774]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[139 144]
 [471 131]]
0.3050847457627119
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... FOXA


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.0001
Window: 120
[[190 174]
 [285 236]]
Accuracy: 0.48135593220338985
[0.48135593220338985]
accuracy
Working on news... FOXA


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


1000.0
Window: 120
[[149 215]
 [210 311]]
Accuracy: 0.519774011299435
[0.519774011299435]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[176 188]
 [261 260]]
0.49265536723163844
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... GILD


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.000774263682681127
Window: 120
[[354 107]
 [375  49]]
Accuracy: 0.4553672316384181
[0.4553672316384181]
accuracy
Working on news... GILD


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.3593813663804626
Window: 120
[[123 338]
 [147 277]]
Accuracy: 0.4519774011299435
[0.4519774011299435]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[342 119]
 [351  73]]
0.4689265536723164
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... GOOGL
0.0001
Window: 120
[[196 179]
 [252 147]]
Accuracy: 0.44315245478036175
[0.44315245478036175]
accuracy
Working on news... GOOGL
1291.5496650148827
Window: 120
[[149 226]
 [154 245]]
Accuracy: 0.5090439276485789
[0.5090439276485789]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[187 188]
 [250 149]]
0.43410852713178294
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... HAS
1000.0
Window: 120
[[316 149]
 [177 237]]
Accuracy: 0.6291240045506257
[0.6291240045506257]
accuracy
Working on news... HAS
610.5402296585327
Window: 120
[[183 282]
 [123 291]]
Accuracy: 0.5392491467576792
[0.5392491467576792]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[308 157]
 [113 301]]
0.6928327645051194
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price.

/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.005994842503189409
Window: 120
[[296 153]
 [240 190]]
Accuracy: 0.552901023890785
[0.552901023890785]
accuracy
Working on news... ILMN


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


7.196856730011519
Window: 120
[[129 320]
 [252 178]]
Accuracy: 0.3492605233219568
[0.3492605233219568]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[224 225]
 [251 179]]
0.45847554038680316
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... INCY


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.000774263682681127
Window: 120
[[106 426]
 [ 54 277]]
Accuracy: 0.44380069524913096
[0.44380069524913096]
accuracy
Working on news... INCY


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


10000.0
Window: 120
[[295 237]
 [ 70 261]]
Accuracy: 0.6442641946697567
[0.6442641946697567]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[103 429]
 [ 33 298]]
0.4646581691772885
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... INTC


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


2.782559402207126
Window: 120
[[249  10]
 [626   0]]
Accuracy: 0.28135593220338984
[0.28135593220338984]
accuracy
Working on news... INTC


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


372.7593720314938
Window: 120
[[110 149]
 [280 346]]
Accuracy: 0.5152542372881356
[0.5152542372881356]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[249  10]
 [625   1]]
0.2824858757062147
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... INTU
0.005994842503189409
Window: 120
[[203 215]
 [236 226]]
Accuracy: 0.4875
[0.4875]
accuracy
Working on news... INTU
1291.5496650148827
Window: 120
[[211 207]
 [150 312]]
Accuracy: 0.5943181818181819
[0.5943181818181819]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[162 256]
 [188 274]]
0.4954545454545455
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... ISRG
2.6826957952797255
Window: 120
[[340  13]
 [502  19]]
Accuracy: 0.4107551487414188
[0.4107551487414188]
accuracy
Working on news... ISRG
0.3593813663804626
Window: 120
[[180 173]
 [144 377]]
Accuracy: 0.6372997711670481
[0.6372997711670481]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[323  30]
 [425  96]]
0.4794050343249428
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price..

/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


1.0
Window: 120
[[  0 421]
 [  0 458]]
Accuracy: 0.5210466439135382
[0.5210466439135382]
accuracy
Working on news... JBHT


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


1.0
Window: 120
[[ 79 342]
 [174 284]]
Accuracy: 0.4129692832764505
[0.4129692832764505]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[  0 421]
 [  0 458]]
0.5210466439135382
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... JD
0.005994842503189409
Window: 120
[[312 171]
 [208 194]]
Accuracy: 0.5717514124293785
[0.5717514124293785]
accuracy
Working on news... JD
0.3593813663804626
Window: 120
[[354 129]
 [240 162]]
Accuracy: 0.5830508474576271
[0.5830508474576271]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[365 118]
 [218 184]]
0.6203389830508474
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... KHC
10000.0
Window: 120
[[180 514]
 [ 40 151]]
Accuracy: 0.37401129943502825
[0.37401129943502825]
accuracy
Working on news... KHC
0.046415888336127774
Window: 120
[[463 231]
 [131  60]]
Accuracy: 0.5909604519774011
[0.5909604519774011]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[459 235]
 [130  61]]
0.5875706214689266
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... K

/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


166.81005372000558
Window: 120
[[459  93]
 [306  21]]
Accuracy: 0.5460750853242321
[0.5460750853242321]
accuracy
Working on news... LBTYA


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.3593813663804626
Window: 120
[[331 221]
 [304  23]]
Accuracy: 0.40273037542662116
[0.40273037542662116]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[452 100]
 [317  10]]
0.5255972696245734
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... LRCX
1.0
Window: 120
[[395  10]
 [415  65]]
Accuracy: 0.519774011299435
[0.519774011299435]
accuracy
Working on news... LRCX
0.046415888336127774
Window: 120
[[259 146]
 [240 240]]
Accuracy: 0.5638418079096045
[0.5638418079096045]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[386  19]
 [399  81]]
0.5276836158192091
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... MAR
0.0001
Window: 120
[[ 59 306]
 [126 394]]
Accuracy: 0.511864406779661
[0.511864406779661]
accuracy
Working on news... MAR
1000.0
Window: 120
[[181 184]
 [131 389]]
Accuracy: 0.6440677966101694
[0.6440677966101694]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[ 68 297]
 [133 387]]
0.5141242937853108
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... MAT
610.54022965

/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.3593813663804626
Window: 120
[[405  23]
 [376  75]]
Accuracy: 0.5460750853242321
[0.5460750853242321]
accuracy
Working on news... MNST


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.000774263682681127
Window: 120
[[254 174]
 [ 47 404]]
Accuracy: 0.7485779294653014
[0.7485779294653014]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[349  79]
 [236 215]]
0.6416382252559727
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... MSFT
1291.5496650148827
Window: 120
[[159 150]
 [371 205]]
Accuracy: 0.41129943502824856
[0.41129943502824856]
accuracy
Working on news... MSFT
10000.0
Window: 120
[[152 157]
 [294 282]]
Accuracy: 0.4903954802259887
[0.4903954802259887]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[155 154]
 [367 209]]
0.41129943502824856
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... MU
10000.0
Window: 120
[[144 185]
 [356 200]]
Accuracy: 0.3887005649717514
[0.3887005649717514]
accuracy
Working on news... MU
0.046415888336127774
Window: 120
[[110 219]
 [242 314]]
Accuracy: 0.47909604519774013
[0.47909604519774013]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[111 218]
 [256 300]]
0.46440677966101696
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on 

/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.000774263682681127
Window: 120
[[165 367]
 [113 235]]
Accuracy: 0.45454545454545453
[0.45454545454545453]
accuracy
Working on news... MYL


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.000774263682681127
Window: 120
[[417 115]
 [272  76]]
Accuracy: 0.5602272727272727
[0.5602272727272727]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[316 216]
 [230 118]]
0.49318181818181817
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... NFLX
10000.0
Window: 120
[[  1 237]
 [ 26 621]]
Accuracy: 0.7028248587570621
[0.7028248587570621]
accuracy
Working on news... NFLX
10000.0
Window: 120
[[121 117]
 [325 322]]
Accuracy: 0.5005649717514125
[0.5005649717514125]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[  2 236]
 [ 46 601]]
0.6813559322033899
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... NTES
0.3593813663804626
Window: 120
[[434  95]
 [234 122]]
Accuracy: 0.6282485875706215
[0.6282485875706215]
accuracy
Working on news... NTES
610.5402296585327
Window: 120
[[440  89]
 [277  79]]
Accuracy: 0.5864406779661017
[0.5864406779661017]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[467  62]
 [261  95]]
0.6350282485875707
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on pric

/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.3593813663804626
Window: 120
[[475   0]
 [404   1]]
Accuracy: 0.5409090909090909
[0.5409090909090909]
accuracy
Working on news... ORLY


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


4.39397056076079
Window: 120
[[361 114]
 [109 296]]
Accuracy: 0.7465909090909091
[0.7465909090909091]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[475   0]
 [403   2]]
0.5420454545454545
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... PAYX


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


11.787686347935873
Window: 120
[[454  10]
 [404   6]]
Accuracy: 0.5263157894736842
[0.5263157894736842]
accuracy
Working on news... PAYX


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.046415888336127774
Window: 120
[[ 32 432]
 [ 36 374]]
Accuracy: 0.4645308924485126
[0.4645308924485126]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[438  26]
 [375  35]]
0.5411899313501144
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... PCAR


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


10000.0
Window: 120
[[191 167]
 [263 253]]
Accuracy: 0.5080091533180778
[0.5080091533180778]
accuracy
Working on news... PCAR


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


227.58459260747887
Window: 120
[[ 75 283]
 [159 357]]
Accuracy: 0.494279176201373
[0.494279176201373]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[ 64 294]
 [153 363]]
0.488558352402746
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... PCLN
166.81005372000558
Window: 120
[[205 169]
 [166 307]]
Accuracy: 0.6044864226682408
[0.6044864226682408]
accuracy
Working on news... PCLN
10000.0
Window: 120
[[139 235]
 [148 325]]
Accuracy: 0.5478158205430933
[0.5478158205430933]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[154 220]
 [138 335]]
0.577331759149941
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... PYPL
1.637893706954064
Window: 120
[[344   0]
 [536   5]]
Accuracy: 0.3943502824858757
[0.3943502824858757]
accuracy
Working on news... PYPL
2.782559402207126
Window: 120
[[ 99 245]
 [279 262]]
Accuracy: 0.40790960451977404
[0.40790960451977404]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[344   0]
 [536   5]]
0.3943502824858757
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on

/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


1291.5496650148827
Window: 120
[[176 320]
 [169 220]]
Accuracy: 0.44745762711864406
[0.44745762711864406]
accuracy
Working on news... QCOM


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.0001
Window: 120
[[394 102]
 [277 112]]
Accuracy: 0.5717514124293785
[0.5717514124293785]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[372 124]
 [234 155]]
0.5954802259887005
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... REGN


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


10000.0
Window: 120
[[115 347]
 [ 75 346]]
Accuracy: 0.522083805209513
[0.522083805209513]
accuracy
Working on news... REGN


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


1.0
Window: 120
[[365  97]
 [260 161]]
Accuracy: 0.5956964892412231
[0.5956964892412231]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[265 197]
 [165 256]]
0.5900339750849377
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... ROST


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.3593813663804626
Window: 120
[[  0 460]
 [  0 425]]
Accuracy: 0.480225988700565
[0.480225988700565]
accuracy
Working on news... ROST


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.005994842503189409
Window: 120
[[ 34 426]
 [ 63 362]]
Accuracy: 0.44745762711864406
[0.44745762711864406]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[  0 460]
 [  0 425]]
0.480225988700565
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... SBUX
11.787686347935873
Window: 120
[[255 193]
 [166 271]]
Accuracy: 0.5943502824858757
[0.5943502824858757]
accuracy
Working on news... SBUX
1.0
Window: 120
[[165 283]
 [230 207]]
Accuracy: 0.42033898305084744
[0.42033898305084744]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[225 223]
 [153 284]]
0.5751412429378531
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... SHPG


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.046415888336127774
Window: 120
[[220 318]
 [107 234]]
Accuracy: 0.5164960182025028
[0.5164960182025028]
accuracy
Working on news... SHPG


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.000774263682681127
Window: 120
[[  0 538]
 [122 219]]
Accuracy: 0.24914675767918087
[0.24914675767918087]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[ 38 500]
 [ 72 269]]
0.3492605233219568
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... SIRI
0.3593813663804626
Window: 120
[[187  32]
 [431 235]]
Accuracy: 0.4768361581920904
[0.4768361581920904]
accuracy
Working on news... SIRI
1.0
Window: 120
[[121  98]
 [638  28]]
Accuracy: 0.16836158192090395
[0.16836158192090395]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[171  48]
 [550 116]]
0.32429378531073444
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... STX


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


1.0
Window: 120
[[ 11 183]
 [ 69 616]]
Accuracy: 0.7133105802047781
[0.7133105802047781]
accuracy
Working on news... STX


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


1.637893706954064
Window: 120
[[ 63 131]
 [334 351]]
Accuracy: 0.4709897610921502
[0.4709897610921502]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[ 12 182]
 [143 542]]
0.6302616609783845
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... SWKS


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


610.5402296585327
Window: 120
[[ 55 247]
 [307 265]]
Accuracy: 0.36613272311212813
[0.36613272311212813]
accuracy
Working on news... SWKS


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


1.637893706954064
Window: 120
[[ 45 257]
 [201 371]]
Accuracy: 0.4759725400457666
[0.4759725400457666]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[ 37 265]
 [230 342]]
0.43363844393592677
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... SYMC


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


10000.0
Window: 120
[[259 305]
 [103 202]]
Accuracy: 0.5304948216340621
[0.5304948216340621]
accuracy
Working on news... SYMC


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.046415888336127774
Window: 120
[[294 270]
 [277  28]]
Accuracy: 0.3705408515535098
[0.3705408515535098]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[335 229]
 [268  37]]
0.428078250863061
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... TMUS
84.83428982440716
Window: 120
[[330  78]
 [200 277]]
Accuracy: 0.6858757062146893
[0.6858757062146893]
accuracy
Working on news... TMUS
10000.0
Window: 120
[[104 304]
 [207 270]]
Accuracy: 0.42259887005649716
[0.42259887005649716]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[266 142]
 [190 287]]
0.6248587570621469
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... TSCO


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


4.39397056076079
Window: 120
[[266 344]
 [101 163]]
Accuracy: 0.49084668192219677
[0.49084668192219677]
accuracy
Working on news... TSCO


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


166.81005372000558
Window: 120
[[408 202]
 [197  67]]
Accuracy: 0.5434782608695652
[0.5434782608695652]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[396 214]
 [132 132]]
0.6041189931350115
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... TSLA
166.81005372000558
Window: 120
[[304 145]
 [166 270]]
Accuracy: 0.6485875706214689
[0.6485875706214689]
accuracy
Working on news... TSLA
1.0
Window: 120
[[139 310]
 [242 194]]
Accuracy: 0.376271186440678
[0.376271186440678]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[160 289]
 [217 219]]
0.42824858757062145
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... TXN
0.000774263682681127
Window: 120
[[181 282]
 [262 154]]
Accuracy: 0.38111490329920367
[0.38111490329920367]
accuracy
Working on news... TXN
21.54434690031882
Window: 120
[[130 333]
 [ 70 346]]
Accuracy: 0.5415244596131968
[0.5415244596131968]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[ 95 368]
 [180 236]]
0.37656427758816835
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working o

/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


0.3593813663804626
Window: 120
[[405   6]
 [363 106]]
Accuracy: 0.5806818181818182
[0.5806818181818182]
accuracy
Working on news... VIAB


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


11.787686347935873
Window: 120
[[213 198]
 [206 263]]
Accuracy: 0.5409090909090909
[0.5409090909090909]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[353  58]
 [327 142]]
0.5625
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... VOD


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


2.782559402207126
Window: 120
[[168 384]
 [ 88 240]]
Accuracy: 0.4636363636363636
[0.4636363636363636]
accuracy
Working on news... VOD


/home/andrea/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)


166.81005372000558
Window: 120
[[274 278]
 [130 198]]
Accuracy: 0.5363636363636364
[0.5363636363636364]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[185 367]
 [ 70 258]]
0.5034090909090909
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... VRSK
10000.0
Window: 120
[[157 146]
 [271 305]]
Accuracy: 0.5255972696245734
[0.5255972696245734]
accuracy
Working on news... VRSK
0.000774263682681127
Window: 120
[[ 53 250]
 [ 97 479]]
Accuracy: 0.6052332195676906
[0.6052332195676906]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[ 82 221]
 [143 433]]
0.5858930602957907
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price... VRTX
0.3593813663804626
Window: 120
[[338  15]
 [487  45]]
Accuracy: 0.4327683615819209
[0.4327683615819209]
accuracy
Working on news... VRTX
1.0
Window: 120
[[ 32 321]
 [  9 523]]
Accuracy: 0.6271186440677966
[0.6271186440677966]
accuracy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[[314  39]
 [430 102]]
0.47005649717514125
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Working on price..